modLoader="javafml"
loaderVersion="[1,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/EyesInTheDarkness/issues"

[[mods]]
modId="eyesinthedarkness"
version="${file.jarVersion}"
displayName="Eyes in the Darkness"
authors="gigaherz"
description='''
Those eyes you think you saw when walking through the forest at night. No, you did not imagine them.
'''
displayURL="https://github.com/gigaherz/EyesInTheDarkness"
logoFile="logo.png"

[[dependencies.eyesinthedarkness]]
   modId="neoforge"
   type="required"
   versionRange="[20.5.0-beta,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.eyesinthedarkness]]
   modId="minecraft"
   type="required"
   versionRange="[1.20.5,1.21)"
   ordering="NONE"
   side="BOTH"