@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.eyes.config;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;