@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.eyes.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;