@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.eyes.client.objentity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;